/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface ShortStory {
    'knobs': string;
    'name': string;
    'renderFunc': string;
    'showWidth': boolean;
    'theme': string;
  }
  interface ShortStoryAttributes extends StencilHTMLAttributes {
    'knobs'?: string;
    'name'?: string;
    'renderFunc'?: string;
    'showWidth'?: boolean;
    'theme'?: string;
  }

  interface SsyBooleanInput {
    'defaultValue': any;
    'label': string;
    'propName': string;
    'updateValue': any;
  }
  interface SsyBooleanInputAttributes extends StencilHTMLAttributes {
    'defaultValue'?: any;
    'label'?: string;
    'propName'?: string;
    'updateValue'?: any;
  }

  interface SsyEnumInput {
    'defaultValue': any;
    'label': string;
    'optionTitles': string[];
    'options': string[];
    'propName': string;
    'updateValue': any;
  }
  interface SsyEnumInputAttributes extends StencilHTMLAttributes {
    'defaultValue'?: any;
    'label'?: string;
    'optionTitles'?: string[];
    'options'?: string[];
    'propName'?: string;
    'updateValue'?: any;
  }

  interface SsyInputLabel {
    'label': string;
    'propName': string;
    'type': string;
  }
  interface SsyInputLabelAttributes extends StencilHTMLAttributes {
    'label'?: string;
    'propName'?: string;
    'type'?: string;
  }

  interface SsyMeasure {
    'content': any;
    'theme': string;
  }
  interface SsyMeasureAttributes extends StencilHTMLAttributes {
    'content'?: any;
    'theme'?: string;
  }

  interface SsyNumberInput {
    'defaultValue': any;
    'label': string;
    'max': number;
    'min': number;
    'propName': string;
    'range': boolean;
    'step': number;
    'updateValue': any;
  }
  interface SsyNumberInputAttributes extends StencilHTMLAttributes {
    'defaultValue'?: any;
    'label'?: string;
    'max'?: number;
    'min'?: number;
    'propName'?: string;
    'range'?: boolean;
    'step'?: number;
    'updateValue'?: any;
  }

  interface SsyStringInput {
    'defaultValue': any;
    'label': string;
    'propName': string;
    'textarea': boolean;
    'updateValue': any;
  }
  interface SsyStringInputAttributes extends StencilHTMLAttributes {
    'defaultValue'?: any;
    'label'?: string;
    'propName'?: string;
    'textarea'?: boolean;
    'updateValue'?: any;
  }
}

declare global {
  interface StencilElementInterfaces {
    'ShortStory': Components.ShortStory;
    'SsyBooleanInput': Components.SsyBooleanInput;
    'SsyEnumInput': Components.SsyEnumInput;
    'SsyInputLabel': Components.SsyInputLabel;
    'SsyMeasure': Components.SsyMeasure;
    'SsyNumberInput': Components.SsyNumberInput;
    'SsyStringInput': Components.SsyStringInput;
  }

  interface StencilIntrinsicElements {
    'short-story': Components.ShortStoryAttributes;
    'ssy-boolean-input': Components.SsyBooleanInputAttributes;
    'ssy-enum-input': Components.SsyEnumInputAttributes;
    'ssy-input-label': Components.SsyInputLabelAttributes;
    'ssy-measure': Components.SsyMeasureAttributes;
    'ssy-number-input': Components.SsyNumberInputAttributes;
    'ssy-string-input': Components.SsyStringInputAttributes;
  }


  interface HTMLShortStoryElement extends Components.ShortStory, HTMLStencilElement {}
  var HTMLShortStoryElement: {
    prototype: HTMLShortStoryElement;
    new (): HTMLShortStoryElement;
  };

  interface HTMLSsyBooleanInputElement extends Components.SsyBooleanInput, HTMLStencilElement {}
  var HTMLSsyBooleanInputElement: {
    prototype: HTMLSsyBooleanInputElement;
    new (): HTMLSsyBooleanInputElement;
  };

  interface HTMLSsyEnumInputElement extends Components.SsyEnumInput, HTMLStencilElement {}
  var HTMLSsyEnumInputElement: {
    prototype: HTMLSsyEnumInputElement;
    new (): HTMLSsyEnumInputElement;
  };

  interface HTMLSsyInputLabelElement extends Components.SsyInputLabel, HTMLStencilElement {}
  var HTMLSsyInputLabelElement: {
    prototype: HTMLSsyInputLabelElement;
    new (): HTMLSsyInputLabelElement;
  };

  interface HTMLSsyMeasureElement extends Components.SsyMeasure, HTMLStencilElement {}
  var HTMLSsyMeasureElement: {
    prototype: HTMLSsyMeasureElement;
    new (): HTMLSsyMeasureElement;
  };

  interface HTMLSsyNumberInputElement extends Components.SsyNumberInput, HTMLStencilElement {}
  var HTMLSsyNumberInputElement: {
    prototype: HTMLSsyNumberInputElement;
    new (): HTMLSsyNumberInputElement;
  };

  interface HTMLSsyStringInputElement extends Components.SsyStringInput, HTMLStencilElement {}
  var HTMLSsyStringInputElement: {
    prototype: HTMLSsyStringInputElement;
    new (): HTMLSsyStringInputElement;
  };

  interface HTMLElementTagNameMap {
    'short-story': HTMLShortStoryElement
    'ssy-boolean-input': HTMLSsyBooleanInputElement
    'ssy-enum-input': HTMLSsyEnumInputElement
    'ssy-input-label': HTMLSsyInputLabelElement
    'ssy-measure': HTMLSsyMeasureElement
    'ssy-number-input': HTMLSsyNumberInputElement
    'ssy-string-input': HTMLSsyStringInputElement
  }

  interface ElementTagNameMap {
    'short-story': HTMLShortStoryElement;
    'ssy-boolean-input': HTMLSsyBooleanInputElement;
    'ssy-enum-input': HTMLSsyEnumInputElement;
    'ssy-input-label': HTMLSsyInputLabelElement;
    'ssy-measure': HTMLSsyMeasureElement;
    'ssy-number-input': HTMLSsyNumberInputElement;
    'ssy-string-input': HTMLSsyStringInputElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
