/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
} from '@stencil/router';


export namespace Components {

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppProfile {
    'match': MatchResults;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface ShortStory {
    'knobs': { [key: string]: any };
    'renderFunc': (any) => any;
    'showWidth': boolean;
  }
  interface ShortStoryAttributes extends StencilHTMLAttributes {
    'knobs'?: { [key: string]: any };
    'renderFunc'?: (any) => any;
    'showWidth'?: boolean;
  }

  interface SsyBooleanInput {
    'defaultValue': any;
    'label': string;
    'propName': string;
    'updateValue': any;
  }
  interface SsyBooleanInputAttributes extends StencilHTMLAttributes {
    'defaultValue'?: any;
    'label'?: string;
    'propName'?: string;
    'updateValue'?: any;
  }

  interface SsyInputLabel {
    'label': string;
    'propName': string;
  }
  interface SsyInputLabelAttributes extends StencilHTMLAttributes {
    'label'?: string;
    'propName'?: string;
  }

  interface SsyNumberInput {
    'defaultValue': any;
    'label': string;
    'max': number;
    'min': number;
    'propName': string;
    'range': boolean;
    'step': number;
    'updateValue': any;
  }
  interface SsyNumberInputAttributes extends StencilHTMLAttributes {
    'defaultValue'?: any;
    'label'?: string;
    'max'?: number;
    'min'?: number;
    'propName'?: string;
    'range'?: boolean;
    'step'?: number;
    'updateValue'?: any;
  }

  interface SsyTextInput {
    'defaultValue': any;
    'label': string;
    'propName': string;
    'textarea': boolean;
    'updateValue': any;
  }
  interface SsyTextInputAttributes extends StencilHTMLAttributes {
    'defaultValue'?: any;
    'label'?: string;
    'propName'?: string;
    'textarea'?: boolean;
    'updateValue'?: any;
  }

  interface SsyWidthMeasure {
    'content': any;
  }
  interface SsyWidthMeasureAttributes extends StencilHTMLAttributes {
    'content'?: any;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppHome': Components.AppHome;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
    'ShortStory': Components.ShortStory;
    'SsyBooleanInput': Components.SsyBooleanInput;
    'SsyInputLabel': Components.SsyInputLabel;
    'SsyNumberInput': Components.SsyNumberInput;
    'SsyTextInput': Components.SsyTextInput;
    'SsyWidthMeasure': Components.SsyWidthMeasure;
  }

  interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
    'short-story': Components.ShortStoryAttributes;
    'ssy-boolean-input': Components.SsyBooleanInputAttributes;
    'ssy-input-label': Components.SsyInputLabelAttributes;
    'ssy-number-input': Components.SsyNumberInputAttributes;
    'ssy-text-input': Components.SsyTextInputAttributes;
    'ssy-width-measure': Components.SsyWidthMeasureAttributes;
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLShortStoryElement extends Components.ShortStory, HTMLStencilElement {}
  var HTMLShortStoryElement: {
    prototype: HTMLShortStoryElement;
    new (): HTMLShortStoryElement;
  };

  interface HTMLSsyBooleanInputElement extends Components.SsyBooleanInput, HTMLStencilElement {}
  var HTMLSsyBooleanInputElement: {
    prototype: HTMLSsyBooleanInputElement;
    new (): HTMLSsyBooleanInputElement;
  };

  interface HTMLSsyInputLabelElement extends Components.SsyInputLabel, HTMLStencilElement {}
  var HTMLSsyInputLabelElement: {
    prototype: HTMLSsyInputLabelElement;
    new (): HTMLSsyInputLabelElement;
  };

  interface HTMLSsyNumberInputElement extends Components.SsyNumberInput, HTMLStencilElement {}
  var HTMLSsyNumberInputElement: {
    prototype: HTMLSsyNumberInputElement;
    new (): HTMLSsyNumberInputElement;
  };

  interface HTMLSsyTextInputElement extends Components.SsyTextInput, HTMLStencilElement {}
  var HTMLSsyTextInputElement: {
    prototype: HTMLSsyTextInputElement;
    new (): HTMLSsyTextInputElement;
  };

  interface HTMLSsyWidthMeasureElement extends Components.SsyWidthMeasure, HTMLStencilElement {}
  var HTMLSsyWidthMeasureElement: {
    prototype: HTMLSsyWidthMeasureElement;
    new (): HTMLSsyWidthMeasureElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
    'short-story': HTMLShortStoryElement
    'ssy-boolean-input': HTMLSsyBooleanInputElement
    'ssy-input-label': HTMLSsyInputLabelElement
    'ssy-number-input': HTMLSsyNumberInputElement
    'ssy-text-input': HTMLSsyTextInputElement
    'ssy-width-measure': HTMLSsyWidthMeasureElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'short-story': HTMLShortStoryElement;
    'ssy-boolean-input': HTMLSsyBooleanInputElement;
    'ssy-input-label': HTMLSsyInputLabelElement;
    'ssy-number-input': HTMLSsyNumberInputElement;
    'ssy-text-input': HTMLSsyTextInputElement;
    'ssy-width-measure': HTMLSsyWidthMeasureElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
